"""Export FastAPI OpenAPI and generated TypeScript schema types."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.api.app import create_app  # noqa: E402
from src.daemon.service import DaemonRunner  # noqa: E402

OPENAPI_PATH = ROOT / "docs" / "openapi.json"
TYPES_PATH = ROOT / "frontend" / "lib" / "generated" / "api-types.ts"


def build_openapi_spec() -> dict[str, Any]:
    app = create_app(DaemonRunner())
    return app.openapi()


def _ts_string(value: str) -> str:
    return json.dumps(value)


def _schema_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _schema_ref_name(str(schema["$ref"]))

    if "const" in schema:
        value = schema["const"]
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        return _ts_string(str(value))

    if "enum" in schema:
        values = schema["enum"]
        if not values:
            return "never"
        return " | ".join("null" if value is None else _ts_string(str(value)) for value in values)

    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return _union_to_ts(schema[union_key])

    if "allOf" in schema:
        return " & ".join(_schema_to_ts(item) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return _union_to_ts([{"type": item} for item in schema_type])

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _schema_to_ts(schema.get("items", {}))
        if " | " in item_type or " & " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema:
        return _object_to_ts(schema)

    return "unknown"


def _union_to_ts(items: list[dict[str, Any]]) -> str:
    rendered = []
    for item in items:
        ts_type = _schema_to_ts(item)
        if ts_type not in rendered:
            rendered.append(ts_type)
    return " | ".join(rendered) if rendered else "unknown"


def _object_to_ts(schema: dict[str, Any]) -> str:
    properties = schema.get("properties") or {}
    additional = schema.get("additionalProperties")

    if not properties:
        if isinstance(additional, dict):
            return f"Record<string, {_schema_to_ts(additional)}>"
        return "Record<string, unknown>"

    required = set(schema.get("required") or [])
    lines = ["{"]
    for name, prop_schema in properties.items():
        optional = "" if name in required else "?"
        lines.append(f"  {_ts_string(str(name))}{optional}: {_schema_to_ts(prop_schema)};")
    if isinstance(additional, dict):
        lines.append(f"  [key: string]: {_schema_to_ts(additional)};")
    lines.append("}")
    return "\n".join(lines)


def render_types(spec: dict[str, Any]) -> str:
    schemas = spec.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_openapi_types.py. Do not edit by hand.",
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"export type {name} = {_schema_to_ts(schemas[name])};")
        lines.append("")
    lines.append("export type ApiSchemas = {")
    for name in sorted(schemas):
        lines.append(f"  {_ts_string(name)}: {name};")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate OpenAPI JSON and frontend TypeScript types.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()

    spec = build_openapi_spec()
    openapi_json = json.dumps(spec, indent=2, sort_keys=True) + "\n"
    types_ts = render_types(spec)

    if args.check:
        stale = []
        if _read(OPENAPI_PATH) != openapi_json:
            stale.append(str(OPENAPI_PATH.relative_to(ROOT)))
        if _read(TYPES_PATH) != types_ts:
            stale.append(str(TYPES_PATH.relative_to(ROOT)))
        if stale:
            print("Generated API contract files are stale:")
            for path in stale:
                print(f"  - {path}")
            print("Run: uv run python scripts/generate_openapi_types.py")
            return 1
        print("Generated API contract files are up to date.")
        return 0

    changed = [
        path
        for path, content in ((OPENAPI_PATH, openapi_json), (TYPES_PATH, types_ts))
        if _write_if_changed(path, content)
    ]
    if changed:
        for path in changed:
            print(f"wrote {path.relative_to(ROOT)}")
    else:
        print("generated files already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
